### ISSUE TITLE
Crash Cinnamon in Linux mint 18

### ISSUE THREAD

**Issue by denegny** [rjanja/desktop-capture#47] opened 2016-07-03 18:10 UTC
Install Mint 18
After capture Cinnamon crash

Cinnamon 3.0.6

**Comment by imarkskinner** [comment] 2016-07-07 19:44
Yeah same for me, crashes every single time. A work around is to change the screen capture program in the applets settings but for me all the others have quirks I don't like so hopefully this one gets fixed because I love this applet.

**Comment by munhyunsu** [comment] 2016-07-25 04:58
Same for me!

**Comment by kartikgola** [comment] 2016-08-01 16:34
No fix yet!

**Comment by rjanja** [comment] 2016-08-01 16:58
Considering that this is a problem with Cinnamon and not this applet, there is no easy way to trace down the error causing the crashing. 

At the very least I would need a debug report of installed video drivers and what versions of Cinnamon and its dependencies you are running.

I would love to fix the crashing behavior you are seeing. You could file a ticket against Cinnamon if you like, as this applet is only triggering built-in Cinnamon functionality when the crash occurs, and I would certainly take a look.

**Comment by itzexor** [comment] 2016-10-05 21:44
Partial trace as I don't have all the debug symbols. This is on cinnamon master:

```
Thread 1 "cinnamon" received signal SIGSEGV, Segmentation fault.
0x00007ffff5f66d2e in __strstr_sse2 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff5f66d2e in __strstr_sse2 () from /usr/lib/libc.so.6
#1  0x00007ffff7b80720 in cinnamon_screen_grabber_grab (grabber=grabber@entry=0x1f8a790, x=x@entry=1968, y=y@entry=51, width=width@entry=974, height=height@entry=655)
    at cinnamon-screen-grabber.c:101
#2  0x00007ffff7b7fb07 in do_grab_screenshot (screenshot_data=screenshot_data@entry=0x2a40960, x=1968, y=51, width=974, height=655) at cinnamon-screenshot.c:99
#3  0x00007ffff7b7ff06 in grab_area_screenshot (stage=0xd0ae00, screenshot_data=0x2a40960) at cinnamon-screenshot.c:236
#4  0x00007ffff67bdf85 in g_closure_invoke () from /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff67d0063 in ?? () from /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff67d8bfc in g_signal_emit_valist () from /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff67d8fdf in g_signal_emit () from /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff711c21b in clutter_actor_continue_paint () from /usr/lib/libclutter-1.0.so.0
#9  0x00007ffff71223db in ?? () from /usr/lib/libclutter-1.0.so.0
#10 0x00007ffff7178edb in ?? () from /usr/lib/libclutter-1.0.so.0
#11 0x00007ffff710a809 in ?? () from /usr/lib/libclutter-1.0.so.0
#12 0x00007ffff7177707 in ?? () from /usr/lib/libclutter-1.0.so.0
#13 0x00007ffff7161459 in ?? () from /usr/lib/libclutter-1.0.so.0
#14 0x00007ffff64e8e67 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#15 0x00007ffff64e90d0 in ?? () from /usr/lib/libglib-2.0.so.0
#16 0x00007ffff64e93f2 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#17 0x00007ffff78d46d4 in meta_run () at core/main.c:542
#18 0x0000000000401bce in main (argc=<optimized out>, argv=<optimized out>) at main.c:329
```

**Comment by itzexor** [comment] 2016-10-05 21:47
Oops, I actually meant to put that on the Cinnamon issue not here. Sorry about that.

**Comment by rjanja** [comment] 2016-10-05 21:48
@itzexor thanks - if you could provide details of what graphics card and driver version you are running, that would be helpful to have alongside the segfault

**Comment by itzexor** [comment] 2016-10-05 21:58
For others following along, I responded here https://github.com/linuxmint/Cinnamon/issues/5524

**Comment by leigh123linux** [comment] 2016-11-13 12:43
Fixed in cinnamon-3.2.0

https://github.com/linuxmint/Cinnamon/pull/5777

**Comment by graineri** [comment] 2016-11-17 23:15
I'm having a similar issue in Cinnamon 3.2.1 using LMDE2. It does not actually crash but it looks as if it creates an overlay on the screens and the only place I can click on is the panel and clicking over the "Desktop Capture" menu does nothing.

The only way to get control back is by restarting Cinnamon. It used to work correctly until the last Cinnamon upgrade.

**Comment by leigh123linux** [comment] 2016-11-18 00:41
@graineri 

Without a backtrace or logging your issue doesn't exist.

**Comment by graineri** [comment] 2016-11-18 00:59
I would be more than glad to provide anything that could be helpful.

Could you please point me out where I can find any desktop capture logs? (or at least, any other log or backtrace that can help here)

**Comment by rjanja** [comment] 2016-12-27 20:21
Hi, I've pushed an update to this applet as 1.06 that should resolve the compatibility problems with Cinnamon 3.2 (and possibly previous versions). Please let me know if this resolves the issue for you. Thanks!

**Comment by graineri** [comment] 2016-12-28 11:33
Hi Rob!
Now the issue is gone. However, I cannot take screenshots and this is what I'm getting logged:
`info t=2016-12-28T11:29:35.580Z Save folder does not exist: /home/graineri/file:/home/graineri/Pictures/screenshots, aborting`

I tried changing the folder with no luck.

Thanks!

**Comment by rjanja** [comment] 2016-12-28 18:49
Hi @graineri, thanks for the feedback. I was able to reproduce that as well. I've pushed another update as 1.08. Could you update your local version of the applet and give it another try? Thanks!

**Comment by graineri** [comment] 2016-12-28 18:58
Hi @rjanja! Thanks for the quick response.

Now it works but only with the predefined screenshots location. If I change it, I get the same log message as before.

**Comment by graineri** [comment] 2016-12-29 12:24
Hi @rjanja! I'm not sure what I did wrong before but now it's working.

**Comment by rjanja** [comment] 2016-12-29 22:02
Oh that's great to hear @graineri! Thanks for the feedback!

**Closed** 2016-12-29 22:02 UTC
